on:
  push:
    branches:
      - main
permissions:
  id-token: write
jobs:
  tf-apply:
    name: Terraform Apply
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '1'
      - uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::374353987873:role/oxide-gh-deployment
          aws-region: us-west-2
      - run: sudo apt update && sudo apt install -y gnupg
      - run: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - run: sudo apt update && sudo apt install -y terraform
      - working-directory: infra
        run: terraform init && terraform apply -auto-approve
      - name: Annotate Grafana
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GRAFANA_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "text": "Deploy ${{ github.sha }}",
              "tags": ["deploy", "terraform"],
              "time": '"$(date +%s%3N)"'
            }' \
            https://sodle.grafana.net/api/annotations
